### ISSUE TITLE
Add ability to List/Get a Task

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry-incubator/eirini#107]
### Description
The CF API <--> Eirini tasks sync loop doesn't work right now (see https://github.com/cloudfoundry/cf-for-k8s/issues/412) because the process is unable to list all tasks that Eirini knows about _and_ is unable to get a single task back from Eirini.

### Steps to reproduce

This manifests via the Tasks Sync loop not being able to reconcile tasks. The user-facing reproduction steps are described in https://github.com/cloudfoundry/cf-for-k8s/issues/412. Essentially if a task completion callback doesn't successfully reach the CF API the corresponding task will be stuck in the `RUNNING` state forever.

### Suggested fix

Implement the List/Get Task endpoints and the the CF API team can implement the corresponding changes on the Cloud Controller's [OPI Task Client](https://github.com/cloudfoundry/cloud_controller_ng/blob/4e53f80fc77c75147d3347e46eaede9b8ea35577/lib/cloud_controller/opi/task_client.rb#L24-L30).

### Additional information (optional)
* https://github.com/cloudfoundry/cloud_controller_ng/pull/1588
* Diego BBS docs: https://godoc.org/code.cloudfoundry.org/bbs#ExternalTaskClient

**Comment by tcdowney** [comment]
Also today I learned about the Task CRD (https://github.com/cloudfoundry-incubator/eirini-release/blob/master/helm/eirini/templates/task-crd.yaml), maybe this is something that would be better solved by that.

**Comment by mnitchev** [comment]
Hey  @tcdowney, 

Yes the Task CRD would solve this, provided Cloud Controller consumes our CRDs, but we're not 100% ready to make the switch from our HTTP API to the CRD one. 
In the meantime we have identified this exact issue and we've created a story to implement the list/get [here](https://www.pivotaltracker.com/story/show/174335347) for our HTTP API. The story is still in the icebox, since our PM has been out the past two weeks, but it should get scheduled soon. 
cc @herrjulz
