### ISSUE TITLE
Panic in eirini-metrics

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/eirini#109]
### Description

Trying to bump kubecf to 1.8.0, and I'm getting a panic from `eirini-metrics`.
I must be missing *something*, but I can't tell what.

### Steps to reproduce

Ran using missing config files.

### What was expected to happen

Proper error with a useful error message, no panic.

### What actually happened

 It panics.

### Suggested fix (optional)

  [Fill in]

### Additional information (optional)

```
│ W0904 19:50:16.381331       1 client_config.go:552] Neither --kubeconfig nor --ma │
│ ster was specified.  Using the inClusterConfig.  This might not work.             │
│ W0904 19:50:16.382538       1 client_config.go:552] Neither --kubeconfig nor --ma │
│ ster was specified.  Using the inClusterConfig.  This might not work.             │
│ panic: open : no such file or directory                                           │
│ goroutine 1 [running]:                                                            │
│ code.cloudfoundry.org/eirini/cmd.ExitIfError(...)                                 │
│     code.cloudfoundry.org/eirini@/cmd/commons.go:44                               │
│ main.main()                                                                       │
│     code.cloudfoundry.org/eirini@/cmd/metrics-collector/main.go:45 +0x487         │
│ stream closed    
```

**Comment by jimmykarily** [comment]
This error seems to originate here: https://github.com/cloudfoundry/go-loggregator/blob/v7.4.0/tls.go#L22
and though the missing information is annoying, it can't be fixed in the Eirini code unless we do some validation on existence of those files before we call `NewIngressTLSConfig` here: https://github.com/cloudfoundry-incubator/eirini/blob/master/cmd/metrics-collector/main.go#L40

but having proper error messages propagated from go-loggregator is better practice, after all we can't predict everything that can go wrong with that call.
