### ISSUE TITLE
 Intention of having statefulsets for applications deployed using eirini 

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry-incubator/eirini#63]
### Description

 We deployed eirini on GKE cluster and we see that eirini creates statefulsets for applications but that doesn't have any volumes attached. 
Is there any intend of creating statefulsets because in our environment where we have 250 node GKE cluster, we are not able to deploy beyond 14K statefulsets(indeed cf apps which eirini creates) for which we created an issue in K8s https://github.com/kubernetes/kubernetes/issues/78682 
 
IMHO, we can go for kind deployments instead which even supports rolling updates

**Comment by julz** [comment]
Hi @KesavanKing - we're using `StatefulSets` right now mostly because we want to support the Diego `INSTANCE_INDEX` property which, unfortunately, isn't possible with `Deployment`s. We hope to deprecate this property and move back to `Deployment`s after our initial 'ready for production' milestone (just for this first milestone we've decided to prioritise parity above all else). 

We're super super interested to hear more about your benchmarks and what else you find as you explore higher loads than our initial milestone is intended to cover - please keep us informed (here, slack etc) as you go along!
